### ISSUE TITLE
Mapping stat bug?

### ISSUE THREAD

**Issue by PhrenoVermouth** [smithlabcode/abismal#4]
95.7252 + 43.6224 > 100
but coincidently 56.3776 + 43.6224 = 100
A bug for stat?

```

pairs:
    total_read_pairs: 6242210
    mapped:
        num_mapped: 5975368
        percent_mapped: 95.7252
        num_unique: 3519207
        percent_unique: 56.3776
        ambiguous: 2456161
    unmapped: 2723003
    percent_unmapped: 43.6224
    translocations: 25721
    percent_translocations: 0.41205
mate1:
    total_reads: 2723003
    mapped:
        num_mapped: 2479941
        percent_mapped: 91.0738
        num_unique: 58582
        percent_unique: 2.15137
        ambiguous: 2421359
    unmapped: 243062
    skipped: 0
mate2:
    total_reads: 2723003
    mapped:
        num_mapped: 2479941
        percent_mapped: 91.0738
        num_unique: 70986
        percent_unique: 2.6069
        ambiguous: 2408955
    unmapped: 243062
    skipped: 0
```
